In [0]:
import pandas as pd
import numpy as np 
from sklearn.impute import SimpleImputer
data = pd.read_csv('country.txt',delimiter=',')
data

In [0]:
data.isnull().sum()

In [0]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(data[['Age','Salary']])
data[['Age','Salary']] = imputer.transform(data[['Age','Salary']])
data.isnull().sum()

In [56]:
data

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [57]:
#Verify Numpy version
print(np.__version__)

1.17.5


In [58]:
#Array is similar like Python List data structure
vals = [1,2,3,4,5,6,7,8,9]
n_vals = np.array(vals)
n_vals

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
#single dimensional array
array_1 =np.array([1,2,3])
#2dimensional Array
array_2 =np.array([[1,2,3],[4,5,6]])
print(array_2.dtype)
#3 Dimensional array
array_3 = np.array([[1,2,3],[4,5,6],[7,8,9]],np.int32)
print(array_3.dtype)

int64
int32


In [60]:
print(array_1.itemsize)
sample_float =np.array([[1,2,3],[4,5,6]],dtype=np.float)
print(sample_float.itemsize)
samples_int64 =np.array([[1,2,3],[4,5,6]],dtype=np.int64)
print(samples_int64.itemsize)
samples_complex =np.array([1,2,3],dtype=np.complex128)
print(samples_complex.itemsize)

8
8
8
16


In [61]:
#List to Array & Array to List
List_salary = [20000,50000,75000,65000]
array_salary = np.array(List_salary)
print(array_salary)
print(array_salary.itemsize)
print(array_salary.size)
print(array_salary.shape)
#convert Array to List
salary_list = array_salary.tolist()
print(salary_list)

[20000 50000 75000 65000]
8
4
(4,)
[20000, 50000, 75000, 65000]


In [62]:
#Transpose Array
divisions = np.array([[10,20],[30,40]])
divisions.T

array([[10, 30],
       [20, 40]])

In [63]:
n_vals.dtype

dtype('int64')

In [64]:
salary = np.array([25300.50,75250.75])
print(salary.dtype)

float64


In [65]:
#Addition of values
newvals = n_vals +10
newvals

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [66]:
odd = np.array([1,3,5,7])
even = np.array([2,4,6,8])
print(odd)
print(odd.shape)
print(odd.ndim)
print(even)
print(even.shape)
print(even.ndim)

[1 3 5 7]
(4,)
1
[2 4 6 8]
(4,)
1


In [67]:
dummy = np.array([[1,2],[3,4],[5,6]])
print(dummy.size)
print(dummy.shape)
hdummy = np.hstack(dummy)
print(dummy)
print(hdummy)
vdummy =np.vstack(dummy)
print(vdummy)

6
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [68]:
#Using hstack  : With hstack you can appened data horizontally. This is a very convinient function in Numpy
hordata = np.hstack((odd,even))
print(hordata)

[1 3 5 7 2 4 6 8]


In [0]:
#With vstack you can appened data vertically
print(odd)
print(even)
print(odd.shape)
print(even.shape)
vertdata =np.vstack((odd,even))
print(hordata.shape)
vertdata
print(vertdata.shape)

In [70]:
#Generate random Numbers
rd = np.random.normal(5,0.5,10)
print(rd)

[4.7561855  5.47240923 4.37447536 5.69706647 6.25401615 4.23672503
 5.11070882 4.0141008  6.26343242 5.06827298]


In [71]:
y_range = np.arange(12)
print(y_range)
print(y_range.ndim)
print(y_range.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
(12,)


In [72]:
y_vert = y_range.reshape(2,3,2)
print(y_vert)
print(y_vert.shape)
print(y_vert.ndim)
print(y_vert.size)
print(len(y_vert))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
(2, 3, 2)
3
12
2


In [73]:
import numpy as np
y = np.array(((1,2,3),(4,5,6),(7,8,9)))
y.ndim

2

In [74]:
y.shape

(3, 3)

In [75]:
x = np.arange(20)
print(x)
show_10 =np.where(x<10)
show_20 =np.where(x>10)
print(show_10)
print(show_20)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)
(array([11, 12, 13, 14, 15, 16, 17, 18, 19]),)


In [76]:
#Single Conditions
nums =np.arange(30)
show_even = np.where(nums%2==0)
show_odd = np.where(nums%2==1)
print(show_even)
print(show_odd)

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]),)
(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]),)


In [77]:
#Using Multiple Conditions
showall = np.where((nums > 10) & (nums<20))
showall

(array([11, 12, 13, 14, 15, 16, 17, 18, 19]),)

In [78]:
show_even = np.where((nums%2==0),'even','odd')
print(nums)
print(show_even)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
['even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even'
 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd'
 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd']


In [79]:
xdata = np.arange(9).reshape((3,3))
print(xdata)
print(xdata.size)
print(xdata.shape)
print(xdata.ndim)
show_dummy = np.where(xdata<4,-1,xdata)
print(show_dummy)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
9
(3, 3)
2
[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]


ravel :returns a view of the original array whenever possible.

In [80]:
xdata
xdata_rav = np.ravel(xdata)
print(xdata_rav)


[0 1 2 3 4 5 6 7 8]


Flatten : returns the copy

In [81]:
xdata_flat = xdata.flatten()
print(xdata_flat)
print(xdata_flat.shape)
print(xdata_flat.ndim)
print(xdata_flat.size)

[0 1 2 3 4 5 6 7 8]
(9,)
1
9


In [82]:
xdata_order =xdata_flat.reshape(-1,1)
print(xdata_order)
print(xdata_order.shape)
print(xdata_order.size)


[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(9, 1)
9
